#!/usr/bin/env bash
set -euo pipefail

# hire-junie.sh — Set up a Junie Live instance on Hermes Agent
#
# One command does everything: creates a Hermes profile, installs persona/skills/docs,
# configures Telegram with DM restriction, creates state directories, installs and
# starts the gateway. Mirrors the OpenClaw hire-junie.sh experience.

usage() {
  cat <<'EOF'
Usage:
  hire-junie.sh --telegram-token TOKEN --admin-telegram-id ID [options]

Creates a Junie Live Hermes profile with Telegram gateway, installs all
seed files, and starts the gateway. After success, send /start to the bot.

Required:
  --telegram-token TOKEN      Telegram BotFather token for the Junie bot.
                              Can also be supplied as JUNIE_TELEGRAM_BOT_TOKEN.
  --admin-telegram-id ID      Telegram admin/user id allowed to DM the bot.

Options:
  --profile NAME              Hermes profile name. Default: junie-live
  --seed-dir DIR              Junie seed dir. Default: auto-detected from script location.
  --model MODEL               Main model for the profile. Default: openrouter/anthropic/claude-opus-4.6
  --no-restart                Configure everything but do not start/restart gateway.
  --help                      Show this help.

After it succeeds, open the Junie bot in Telegram and send /start.
EOF
}

log() { printf '%s\n' "$*"; }
err() { printf 'ERROR: %s\n' "$*" >&2; }

need_value() {
  local opt="$1" value="${2:-}"
  [[ -n "$value" && "$value" != --* ]] || { err "$opt requires a value"; exit 2; }
}

TOKEN="${JUNIE_TELEGRAM_BOT_TOKEN:-}"
ADMIN_TELEGRAM_ID=""
PROFILE="junie-live"
SEED_DIR=""
MODEL="openrouter/anthropic/claude-opus-4.6"
RESTART=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERMES_VERSION_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --telegram-token) need_value "$1" "${2:-}"; TOKEN="$2"; shift 2 ;;
    --admin-telegram-id) need_value "$1" "${2:-}"; ADMIN_TELEGRAM_ID="$2"; shift 2 ;;
    --profile) need_value "$1" "${2:-}"; PROFILE="$2"; shift 2 ;;
    --seed-dir) need_value "$1" "${2:-}"; SEED_DIR="$2"; shift 2 ;;
    --model) need_value "$1" "${2:-}"; MODEL="$2"; shift 2 ;;
    --no-restart) RESTART=0; shift ;;
    --help|-h) usage; exit 0 ;;
    *) err "unknown argument: $1"; usage; exit 2 ;;
  esac
done

if [[ -z "$SEED_DIR" || ! -d "$SEED_DIR" ]]; then
  SEED_DIR="$HERMES_VERSION_ROOT/initialization"
fi

log "Will use $SEED_DIR as directory with seed files for Junie Live initialization"

[[ -n "$TOKEN" ]] || { err "missing --telegram-token or JUNIE_TELEGRAM_BOT_TOKEN"; exit 2; }
[[ -n "$ADMIN_TELEGRAM_ID" ]] || { err "missing required --admin-telegram-id"; exit 2; }
[[ -d "$SEED_DIR" ]] || { err "seed dir not found: $SEED_DIR"; exit 1; }
command -v hermes >/dev/null || { err "hermes CLI not found in PATH"; exit 1; }

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
PROFILE_DIR="$HERMES_HOME/profiles/$PROFILE"
STATE_DIR="$HERMES_HOME/junie-live/state"

# ── Step 1: Create profile ──
log "Creating Hermes profile: $PROFILE"
if hermes profile list 2>/dev/null | grep -qE "^\s*[◆◇]\s*$PROFILE\s"; then
  log "Profile $PROFILE already exists, will update in place"
else
  hermes profile create "$PROFILE" --no-alias || { err "Failed to create profile $PROFILE"; exit 1; }
fi

# ── Step 2: Install persona ──
log "Installing persona..."
mkdir -p "$PROFILE_DIR"
cp "$SEED_DIR/persona.md" "$PROFILE_DIR/persona.md"

# ── Step 3: Install skills ──
log "Installing Junie Live skills..."
for skill_dir in "$SEED_DIR/skills"/*/; do
  [[ -f "$skill_dir/SKILL.md" ]] || continue
  skill_name=$(grep '^name:' "$skill_dir/SKILL.md" | head -1 | sed 's/^name:[[:space:]]*//')
  if [[ -n "$skill_name" ]]; then
    target_dir="$PROFILE_DIR/skills/junie-live/$skill_name"
    mkdir -p "$target_dir"
    cp -r "$skill_dir"/* "$target_dir/"
    log "  Installed skill: $skill_name"
  fi
done

# ── Step 4: Copy docs to profile ──
log "Installing seed docs..."
DOCS_DIR="$PROFILE_DIR/junie-live-docs"
mkdir -p "$DOCS_DIR"
if [[ -d "$SEED_DIR/docs" ]]; then
  cp -r "$SEED_DIR/docs"/* "$DOCS_DIR/"
fi

# ── Step 5: Create state directories ──
log "Creating state directories..."
mkdir -p "$STATE_DIR"/{backlog/items,reflections,overnight,logs}

# ── Step 6: Configure Telegram + model in profile .env ──
log "Configuring profile .env..."
PROFILE_ENV="$PROFILE_DIR/.env"
cat > "$PROFILE_ENV" <<ENV
# Junie Live — auto-generated by hire-junie.sh
TELEGRAM_BOT_TOKEN=$TOKEN
TELEGRAM_ALLOWED_USERS=$ADMIN_TELEGRAM_ID
TELEGRAM_ALLOW_ALL_USERS=false
ENV
log "  Telegram configured (DM restricted to admin $ADMIN_TELEGRAM_ID)"

# ── Step 7: Set model in profile config ──
log "Setting model: $MODEL"
hermes -p "$PROFILE" config set model.default "$MODEL" 2>/dev/null || true

# ── Step 8: Install and start gateway ──
if [[ "$RESTART" -eq 1 ]]; then
  log "Installing/restarting gateway..."
  hermes -p "$PROFILE" gateway install --force 2>/dev/null || true
  hermes -p "$PROFILE" gateway restart 2>/dev/null || {
    hermes -p "$PROFILE" gateway start 2>/dev/null || {
      log "Gateway could not start automatically. Run: hermes -p $PROFILE gateway start"
    }
  }
fi

# ── Done ──
log ""
log "Junie Live hiring complete."
log "Profile:          $PROFILE"
log "Profile dir:      $PROFILE_DIR"
log "State dir:        $STATE_DIR"
log "Telegram admin:   $ADMIN_TELEGRAM_ID"
log "Model:            $MODEL"
log ""
log "Next: open the Junie bot in Telegram and send /start."
